backend:
  git:
    uri: git@...
    branch: master
  artifact:
    s3:
      bucket: backend-artifacts
      region_name: eu-west-1
      regexp: backend-(.*).tgz

terraform:
  git:
    uri: git@...
    branch: master
