backend:
  git:
    uri: git@...
    branch: master
  artifact:
    s3:
      bucket: backend-artifacts
      region_name: eu-west-1
      regexp: backend-(.*).tgz

terraform:
  git:
    uri: git@...
    branch: master


backend-git-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  ...
  -----END RSA PRIVATE KEY-----
terraform-git-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  ...
  -----END RSA PRIVATE KEY-----
backend-artifact-aws-key-id: A...
backend-artifact-aws-access-key: C...